#定义service
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service-internal
  labels:
    app: eureka-service-internal
  namespace: eureka
spec:
  clusterIP: None
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka
  type: ClusterIP


---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLables:
      app: eureka
  serviceName: eureka-service-internal
  replicas: 2
  template:
    metadata:
      labels:
        app: eureka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - images: harbor.mofangge.net/english_word/eureka-server:test
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_NODE_NAME
              valueFrom:
                filedRef:
                  filedPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                filedRef:
                  filedPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                filedRef:
                  filedPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                filedRef:
                  filedPath: status.podIP
            - name: MY_IN_SERVICE_NAME
              value: eureka-service-internal
            - name: EUREKA_APPLICATION_NAME
              value: eureka
            - name: EUREKA_REPLICAS
              value: 3
        readinessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds:  120
          periodSeconds: 10
      dnsPolicy: ClusterFirst
