apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
  labels:
    app: nginx-ingress-lb
  name: nginx-ingress-lb
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      nodePort: 30495
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30301
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: ingress-nginx
  type: LoadBalancer
